### ISSUE TITLE
dependency error when specifying manage_virtualenv

### ISSUE THREAD

**Issue by ogdensan** [voxpupuli/puppet-module-puppetboard#101]
Puppet run returns the following dependency error:

Error: Failed to apply catalog: Cannot alias Package[virtualenv] to ["python-virtualenv", :apt] at /etc/puppetlabs/code/environments/production/modules/python/manifests/install.pp:53; resource ["Package", "python-virtualenv", :apt] already declared at /etc/puppetlabs/code/environments/production/modules/puppetboard/manifests/init.pp:268

This is caused by a duplicate declaration of the python-virtualenv package in both puppetboard and python module.

**Comment by jyaworski** [comment]
Fixed by #102
