### ISSUE TITLE
please make a fresh release

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-module-puppetboard#103]
ref: https://github.com/voxpupuli/puppet-module-puppetboard/pull/98

**Comment by dalesit** [comment]
module on puppetforge is very broken - needs a new release

**Comment by zleswomp** [comment]
Yes please.

**Comment by igalic** [comment]
reminder, you call all help with this ;) https://voxpupuli.org/docs/#releasing-a-new-version-of-a-module

**Comment by zleswomp** [comment]
Thanks for the link @igalic.
