### ISSUE TITLE
The parameter 'reports_count' is declared more than once in the parameter list

### ISSUE THREAD

**Issue by clintonm9** [voxpupuli/puppet-module-puppetboard#114]
On a fresh install of this package I get this error when declaring? Is this a bug?

**Comment by jyaworski** [comment]
Are you using the forge version, or the git version?

**Comment by clintonm9** [comment]
I ran "puppet module install puppet-puppetboard" so I am guessing that is forge.

**Comment by jyaworski** [comment]
This is a duplicate of #103 then. Closing. For now, use the git version until we get a forge release out with the fix.
