### ISSUE TITLE
Setting 'PUPPETDB_SSL_VERIFY' via Hiera Fails

### ISSUE THREAD

**Issue by kemra102** [voxpupuli/puppet-module-puppetboard#65]
I am setting the **PUPPETDB_SSL_VERYIFY** via Hiera like so:

```yaml
puppetboard::puppetdb_ssl_verify: '/var/lib/puppet/ssl/certs/ca.pem'
```

However this is being ignored for some reason I can't quite see looking at the code.

For reference this is the full Hiera code for this node (separate node currently to my PuppetDB server):

```yaml
---
classes:
        - apache
        - apache::mod::wsgi
        - puppetboard
        - puppetboard::apache::vhost
apache::mod::wsgi::wsgi_socket_prefix: '/var/run/wsgi'
puppetboard::manage_virtualenv: true
puppetboard::manage_git: true
puppetboard::unresponsive: '6'
puppetboard::puppetdb_host: 'puppetdb.example.com'
puppetboard::puppetdb_port: '8081'
puppetboard::puppetdb_key: "/var/lib/puppet/ssl/private_keys/%{clientcert}.pem"
puppetboard::puppetdb_ssl_verify: '/var/lib/puppet/ssl/certs/ca.pem'
puppetboard::puppetdb_cert: "/var/lib/puppet/ssl/certs/%{clientcert}.pem"
puppetboard::apache::vhost::vhost_name: 'puppetboard.example.com'
puppetboard::apache::vhost::port: 80
```

This creates a **settings.py** of:

```python
DEV_LISTEN_HOST = '127.0.0.1'
DEV_LISTEN_PORT = 5000
LOGLEVEL = 'info'
PUPPETDB_HOST = 'puppetdb.example.com'
PUPPETDB_PORT = 8081
PUPPETDB_SSL_VERIFY = False
PUPPETDB_KEY = '/var/lib/puppet/ssl/private_keys/puppetboard.example.com.pem'
PUPPETDB_CERT = '/var/lib/puppet/ssl/certs/puppetboard.example.com.pem'
PUPPETDB_TIMEOUT = 20
UNRESPONSIVE_HOURS = 6
ENABLE_QUERY = True
LOCALISE_TIMESTAMP = True
PUPPETDB_EXPERIMENTAL = False
REPORTS_COUNT = 10
```

I am using the latest 2.5.0 version of the module from Puppet Forge.

**Comment by nibalizer** [comment]
Hrm, it looks like you're failing the truth test here https://github.com/puppet-community/puppet-module-puppetboard/blob/master/templates/settings.py.erb#L16. Now doing this is a bit weird becaus we can have 'True', 'False', or 'path' so /hrm/

One thing I notice right away is that this is the one field in your hiera that is single quoted. Maybe try double quoting it?

**Comment by nibalizer** [comment]
I don't have the resources to reproduce this today but I'll try to do so in a few days.

**Comment by kemra102** [comment]
Double quoting has no effect (I tried it in my test set-up), though I didn't expect it too. There are other single quoted stings in the config - I only tend to double quote when I need a value expanding like for the name of the cert or the key.

I agree though that it's that test it's failing at I just can't see why that might be the case.

**Comment by nibalizer** [comment]
What puppet version are you using?

**Comment by kemra102** [comment]
A mix of 3.7.3 & 3.7.4 Open Source version (mostly the latter).

**Comment by ffrank** [comment]
I just failed to reproduce. I made

 1. a `hiera.yaml` with

        :backends:
          - yaml
        :yaml:
          :datadir: /etc/puppet/hiera
        :hierarchy:
          - "%{::clientcert}"
          - common

 2. a `common.yaml` with all your `puppetboard data`

I ran `puppet apply -e 'include puppetboard'` and installation succeeded. My `settings.py` includes

    PUPPETDB_SSL_VERIFY = '/var/lib/puppet/ssl/certs/ca.pem'

Puppet version is `3.6.2`.

Have you throughly inspected your Hiera data? (i.e., `hiera` CLI tests)

**Comment by jyaworski** [comment]
Hello:

Is this still an issue?

**Comment by ryno75** [comment]
kemra102,
which version of the puppetboard module are you rocking?  Anything past 6b95a6ae53e7c4fc74ae830fe4123e3fdf7cb15b will ONLY accept a bool for PUPPETDB_SSL_VERIFY.  Which is a bug because it should support bool OR string.
