### ISSUE TITLE
Module version differences

### ISSUE THREAD

**Issue by karooga** [voxpupuli/puppet-module-puppetboard#77]
Hi, 

How is this module different from nibalizer-puppetboard module?  Does this one supersede it or is it just that it supports PE?

regards
Paul

**Comment by rendhalver** [comment]
Hi Paul.

This module supersedes nibalizer-puppetboard.

**Comment by karooga** [comment]
Brilliant thanks!

**Comment by ffrank** [comment]
@nibalizer can you deprecate the old one on the Forge?

**Comment by jyaworski** [comment]
Ping @nibalizer 

https://forge.puppetlabs.com/nibalizer/puppetboard

**Comment by jyaworski** [comment]
Closing due to lack of movement. @nibalizer
