### ISSUE TITLE
progress or next steps for puppet 4 support

### ISSUE THREAD

**Issue by pskrz** [voxpupuli/puppet-module-puppetboard#93]
I'm unsure of the status for puppet 4 support. What kind of steps would need to be taken to support puppet4?

**Comment by nibalizer** [comment]
I am also unsure. Does the module run in puppet4 right now?

**Comment by igalic** [comment]
@nibalizer best way to find out is to modulesync it and let travis do the rest…

**Comment by Jmeyering** [comment]
Puppetboard just pushed puppetdb3 support to master. https://github.com/puppet-community/puppetboard/pull/176

**Comment by jyaworski** [comment]
If I'm not mistaken, this does support puppet4. Is your experience different?

**Comment by igalic** [comment]
@jyaworski we could update the modules .dotfiles and see what travis thinks :3

**Comment by mattock** [comment]
This module seems to work just fine on the following setup:
* puppetserver 2.3.1
* puppetdb 4.0.0
* puppet-agent 1.4.1
* puppet 4.4.1

The puppetserver/puppetdb and puppetboard instances are on Ubuntu 14.04

**Comment by mattock** [comment]
Adding a bit to my earlier comment... I ran my usual battery of checks (includes puppet-lint) on the module and there were no warnings. So this module is definitely fully compatible with Puppet 4.
