### ISSUE TITLE
Documentation wrong on SSL

### ISSUE THREAD

**Issue by jhg03a** [voxpupuli/puppet-module-puppetboard#94]
The frontpage references the parameter "puppetdb_ssl".  It was replaced with "puppetdb_ssl_verify".  At the same time it appears the type was changed from string to bool.  So there isn't a way any longer to specify the CA for the puppetmaster.

**Comment by igalic** [comment]
@jhg03a any chance you can provide a patch?

**Comment by jhg03a** [comment]
It's actually really confusing.  Digging deeper into the python, it appears that the SSL_VERIFY parameter to the puppetdb connection library actually does take a string that points the the CA cert.  I'm not sure what a value of true does.

**Comment by ryno75** [comment]
Indeed... it should be PUPPETDB_SSL_VERIFY (https://github.com/voxpupuli/puppetboard/blob/master/README.rst#id16).  And it should support bool AND string values.  This was changed in 6b95a6ae53e7c4fc74ae830fe4123e3fdf7cb15b and breaks functionality.
I am going to submit a patch.

**Comment by igalic** [comment]
fixed in #99
